### ISSUE TITLE
The game is freezing on Firefox Nightly

### ISSUE THREAD

**Issue by pjoulot** [aframevr/a-blast#107]
Hi,
I run Firefox Nightly with a standard profile on Windows 10 with HTC Vive.

I play some seconds and after a while the game freeze. I don't really know when it crashes, maybe when I try to shoot too fast... It seems that I have some errors with the sound, but the music continue after the game froze.

[Console screenshot
](http://imgur.com/6aBO4Bb)

I hope it will help you. Don't hesitate to ask me more details.

**Comment by machenmusik** [comment]
I believe this is fixed by
https://github.com/aframevr/a-blast/pull/109/commits/ee1f66b8df17552e3d01edf4fb2ae802feeaae25

**Comment by pjoulot** [comment]
The demo https://aframe.io/a-blast/ , is it up-to-date?

I've cloned the repo to be sure I'm with the latest version and test it again. The bug is still there but the error has changed. I'm pretty sure it occurs when I shoot too fast. When I push the trigger not too fast, the game continues normally.

@machenmusik data is the error in the console so I think the bug is related to the part of the code you showed me.

[Console screenshot](http://i.imgur.com/BIJthlR.png
)

**Comment by machenmusik** [comment]
can you try at https://a-blast.herokuapp.com and see if that is fixed?

On January 21, 2017 1:50:26 PM EST, Philippe <notifications@github.com> wrote:
>The demo https://aframe.io/a-blast/ , is it up-to-date?
>
>I've cloned the repo to be sure I'm with the latest version and test it
>again. The bug is still there but the error has changed. I'm pretty
>sure it occurs when I shoot too fast. When I push the trigger not too
>fast, the game continues normally.
>
>@machenmusik data is the error in the console so I think the bug is
>related to the part of the code you showed me.
>
>[Console screenshot](http://i.imgur.com/BIJthlR.png
>)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/aframevr/a-blast/issues/107#issuecomment-274280396

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by pjoulot** [comment]
Adding a test correct the bug and the game seems ok.

I've just tested your url and the bug seems corrected, what did you modified?

**Comment by machenmusik** [comment]
https://github.com/chenzlabs/a-blast/commit/ee1f66b8df17552e3d01edf4fb2ae802feeaae25

On January 21, 2017 2:59:56 PM EST, Philippe <notifications@github.com> wrote:
>Adding a test correct the bug and the game seems ok.
>
>I've just tested your url and the bug seems corrected, what did you
>modified?
>
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/aframevr/a-blast/issues/107#issuecomment-274284554

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by pjoulot** [comment]
Oh ok, I thought this was already merged into master but I've checked and it's not.
Hope it will be soon. Why there is no pull request for this?

This issue can be closed. Thanks for your help @machenmusik
